### ISSUE TITLE
Auto generated help command

### ISSUE THREAD

**Issue by ferrouswheel** [ideegeo/Daemonise#12]
It's cool we can use `$d->hooks` to set up commands easily.

What'd be really awesome is auto adding a help command, which would either:
- with no parameters, just list all the commands (and/or whether it accepts a default/wildcard command).
- with a parameter, return the perldoc for the related hook function (not sure how hard this is in perl?)... or make it easy to provide documentation with the function reference (for inline functions using sub).

Ideally this documentation would include what keys are expected to exist in the message when calling a command, and what keys are changed, but that's not something that can easily be generated without adding some kind of declarative info for each command.

**Comment by nupfel** [comment]
:+1:
i like this. part one should be fairly easy.
part two might be trickier. i can't think of a way to do that out of my head, but i'm sure there is a module for it! ;)

**Comment by ferrouswheel** [comment]
Rereading this, I realise this could interpreted as meaning we should add a command line `--help`.

I think a command line help would be neat, but when I wrote this I was thinking about a "help" RPC, with the answer returned over rabbitmq.

Guess it wouldn't be hard to do both.

The reason I want a help RPC is so that I can just query the services we're running already and don't necessarily need to be in the correct environment to run the service (e.g. if the service is in Docker, it can be annoying to enter the docker container with the correct perl dependencies, and would easier to just say "Hey you service, what do you do??"

**Comment by nupfel** [comment]
yea, i get the idea. i did think first you meant executing the rabbit by itself on the command line was supposed to output the help. but that can simply be used to test the behaviour and let it also output the help via a common `help` command that every rabbit knows of by default. still liking the idea.

**Comment by nupfel** [comment]
@ferrouswheel i wrote some first draft of this in https://github.com/ideegeo/Daemonise/pull/14, it's far from finished. let me show you an example of what works right now:

```
> perl -w -Mstrict -Ilib -MDaemonise -e 'my $d = new Daemonise(debug=>1); $d->load_plugin("JobQueue"); $d->foreground(1); $d->hooks(bla => sub { "blub" }, blub => sub{}); $d->start' help
-e: supported commands: help, bla, blub
{
    response   {
        commands   [
            [0] "help",
            [1] "bla",
            [2] "blub"
        ]
    }
}
```

besides that you can already call help with an argument. you can actually call any hook, not just `help`, from the command line with this. could be useful for testing as well.
as a side effect i had to pull all GetOption related parsing into Daemonise, which i find nicer anyway. i already have a better way/idea for plugins to deal with adding new option flags to `GetOptions()` rather than passing them on via the `parse_command_line()` method in some predefined non-obvious order.

**Comment by ferrouswheel** [comment]
Nice one!

Will this impact the command line parsing for crons and rabbits? I think we may still need to add custom command line options for some of our internal stuff.

**Comment by nupfel** [comment]
it will. basically it will make the defaults obsolete. i can simply add functionality to be able to define custom options. so far parse_command_line() will only get executed when you call `$d->start` and define a named `sub` or a hook to run instead of running code directly. so crons would not be affected at the moment anyway.
